### ISSUE TITLE
App doesn't compile with generic destination on xcodebuild

### ISSUE THREAD

**Issue by emadhegab** [Kolos65/Mockable#11] opened 2024-01-09 17:50 UTC
I try to compile my app using this command
`xcodebuild -scheme 'MyApp'   -sdk 'iphonesimulator' -destination 'generic/platform=iOS Simulator'`

but it gives me error always 

protocos/MyAppService.swift:5:17: external macro implementation type 'MockableMacro.MockableMacro' could not be found for macro 'Mockable()'

It will run fine if changed the destination into -destination 'platform=iOS Simulator,name=iPhone'
but that will prevent me from using the .app file it generates in the E2E testing i have.

**Comment by Kolos65** [comment] 2024-01-16 10:06
I can repro this on an example project, will update you if I find anything.

**Comment by Kolos65** [comment] 2024-01-16 11:04
Not sure why, but what I have found so far is that if you omit the `-sdk 'iphonesimulator'` flag, it compiles... 
Are you sure you need to specify the base SDK explicitly?

**Comment by emadhegab** [comment] 2024-01-16 11:14
I tried. but it crash when dragging the .app to simulator and try to run it. i think without sdk it takes the default which is probably the real device

**Comment by Kolos65** [comment] 2024-04-02 17:26
@emadhegab I will close this for now due to inactivity, will reopen if needed.

**Comment by carlossolana-aily** [comment] 2024-07-30 10:40
Someting similar is happening to me in archiving in the CI:
```
** ARCHIVE FAILED **

The following build commands failed:
	ComputeTargetDependencyGraph
```

If I remove Mockable from all module dependencies, comment imports and macros, then it works. The command looks like:

```
xcodebuild -workspace MyProject.xcworkspace -scheme MyScheme -configuration MyConfig -destination 'generic/platform=iOS' -skipPackagePluginValidation clean archive
```

**Comment by carlossolana-aily** [comment] 2024-08-02 09:40
A minor finding:
If I leave my codebase like this:
```
#if canImport(Mockable)
import Mockable
#endif

#if canImport(Mockable)
@Mockable
#endif
protocol BlaBla {
```

And my Package.swift like this:
```
dependencies: [
        .package(path: "../PackageA"),
        .package(path: "../PackageB"),
        .package(path: "../PackageC"),
        .package(path: "../PackageD"),
        .package(url: "https://github.com/hmlongco/Factory", exact: "2.3.2"),
        .package(url: "https://github.com/Kolos65/Mockable", exact: "0.0.9"),
        .package(url: "https://github.com/realm/SwiftLint", exact: "0.55.1")
    ],
    targets: [
        .target(name: "MyPackage",
                dependencies: ["PackageA", "PackageB", "Factory", "PackageC", "PackageD"/*, .product(name: "Mockable", package: "Mockable")*/],
                path: "Sources",
                swiftSettings: [.define("MOCKING", .when(configuration: .debug))],
                plugins: [.plugin(name: "SwiftLintBuildToolPlugin", package: "SwiftLint")]),
        .testTarget(name: "MyPackageTests", dependencies: ["MyPackage", .product(name: "MockableTest", package: "Mockable")]),
    ]
```

Then it still works on CI, because the produces product is not included in the target, and at the same time is "easy" to activate it (just uncomment that part) without changing the actual codebase.

Still trying to figure out the cause of this issue, I'll use this as a temporary fix.

**Comment by Kolos65** [comment] 2024-08-02 09:49
@carlossolana-aily Have you tried adding `-skipMacroValidation` to the xcodebuild command?

**Comment by carlossolana-aily** [comment] 2024-08-02 10:33
No, I didn't! Now I reverted everything and it works! Thank you very much! :D

**Comment by Kolos65** [comment] 2024-12-17 09:33
Closing this as I don't see any library specific bug or issue here.

**Closed by Kolos65** 2024-12-17 09:33 UTC
Labels: help wanted
