### ISSUE TITLE
Support For Swift 6 Typed Throws

### ISSUE THREAD

**Issue by calebwilson706** [Kolos65/Mockable#63] opened 2024-07-08 11:07 UTC
We recently updated our project to swift 6 and were looking forward to using typed throws. However, Mockable gives us the following error when adding the error type to the functions on our protocol definitions

```
Invalid variable requirement. Missing type annotation or accessor block.
```

**Example Code**
```
enum ExampleError: Error {
    case myError
}

@Mockable
protocol Example {
    func theFunction() throws(ExampleError)
}
```

**Comment by kelvinharron** [comment] 2024-07-08 11:21
@Kolos65 would you accept contributions for this? I'd be happy to progress this with some guidance as we're keen to embrace Swift 6. Thanks!

**Comment by Kolos65** [comment] 2024-07-08 11:23
This is not library issue, swift-syntax 511.x.x cannot parse this new Swift 6 feature and the `throws(ExampleError)` is mistaken to a variable declaration somehow.

This can't be fixed until the official realse of swift-syntax 600.x.x which is currently in [pre-release phase](https://github.com/swiftlang/swift-syntax/releases).

**Comment by Kolos65** [comment] 2024-07-08 11:26
Regardless, adding support for typed throws will not be trivial, we could start implementing that in the meantime.

**Comment by kelvinharron** [comment] 2024-07-08 11:28
Great context to have on the release, thanks @Kolos65 . Any guidance on how we could start? We're loving our time with Mockable and we're keen to help make it even better where we can. 👍

**Comment by Kolos65** [comment] 2024-07-08 11:36
I would start this by first making this work with the above protocol's current expansion (remove the typed throw and copy the `@Mockable` expansion to a source file). After we have a PoC of that, we can implement those changes in the macro.

**Comment by Kolos65** [comment] 2024-07-08 12:25
Added some pre-work in this PR: https://github.com/Kolos65/Mockable/pull/64

**Comment by Kolos65** [comment] 2024-09-28 16:18
@calebwilson706 I have finished implementing this feature, can you guys take a quick look by using the *[feat-add-typed-throws-support](https://github.com/Kolos65/Mockable/tree/feat-add-typed-throws-support)* branch?

**Comment by kelvinharron** [comment] 2024-10-02 09:59
@Kolos65 The flow I tried was to update a protocol to use a typed throw and set a module and its test companion target to use Swift 6. When I look at the `Mocker` class from Mockable, I don't see it pick up the Swift 6 codeblock.

<img width="649" alt="Screenshot 2024-10-02 at 11 57 23" src="https://github.com/user-attachments/assets/a51f72af-47e1-478f-a961-f7e61026f305">

<img width="953" alt="Screenshot 2024-10-02 at 11 58 33" src="https://github.com/user-attachments/assets/986e47f1-bdc3-4c16-8d35-7d7589311b32">

Do you know what I could be missing here? Instead of creating a new app to test this individually, I'm trying to bring it into our existing app because it would be a real world representation other users would share. Thanks!

**Comment by Kolos65** [comment] 2024-10-02 15:34
@kelvinharron Can you check if you see:

```
    swiftLanguageVersions: [.v5, .version("6")]
```

in the Package.swift of your pulled version?

**Comment by kelvinharron** [comment] 2024-10-02 18:24
@Kolos65 confirmed:

```
let package = Package(
    name: "Mockable",
    platforms: [.macOS(.v12), .iOS(.v13), .tvOS(.v13), .watchOS(.v6), .macCatalyst(.v13)],
    products: [
        .library(
            name: "Mockable",
            targets: ["Mockable"]
        )
    ],
    dependencies: ifDev(add: devDependencies) + [
        .package(url: "https://github.com/swiftlang/swift-syntax.git", "509.0.0"..<"601.0.0"),
        .package(url: "https://github.com/pointfreeco/swift-issue-reporting", .upToNextMajor(from: "1.4.1"))
    ],
    targets: ifDev(add: devTargets) + [
        .target(
            name: "Mockable",
            dependencies: [
                "MockableMacro",
                .product(name: "IssueReporting", package: "swift-issue-reporting")
            ],
            plugins: ifDev(add: devPlugins)
        ),
        .macro(
            name: "MockableMacro",
            dependencies: [
                .product(name: "SwiftSyntaxMacros", package: "swift-syntax"),
                .product(name: "SwiftCompilerPlugin", package: "swift-syntax")
            ],
            plugins: ifDev(add: devPlugins)
        )
    ],
    swiftLanguageVersions: [.v5, .version("6")]
)
```

While I can get us to Xcode 16 and iOS 18 easily, I'm not sure how long moving to Swift 6 across the codebase will take. Any thoughts on what I can do to further debug? Keen to help with this ace work you've done (and greatly welcome the removal of MockableTest)! 😃

**Comment by Kolos65** [comment] 2024-10-15 09:43
@kelvinharron so there are other modules that still use swift 5 in the project?

**Comment by kelvinharron** [comment] 2024-10-18 11:04
@Kolos65 yes, it's on our list to migrate them all over. I can't promise a timeline on that with other priorities as we move towards our deadline window. Would you prefer to revisit this another time?

**Comment by Kolos65** [comment] 2024-10-18 11:10
Yeah, I think if you still have some modules that are built with Swift 5 language mode, Mockable won't be compiled with Swift 6. If you get to a point where you can test this in your project, I would love to hear your feedback! I think I will merge this soon anyways.

**Closed** 2024-12-01 21:26 UTC
Labels: bug
